name: First Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Build and Deploy
        env:
          TEST_SECRETS: ${{ secrets.TEST_SECRETS }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: npm install && npm run build
        run: |
            echo $TEST_SECRETS
